### ISSUE TITLE
Improve CSS of the portal.

### ISSUE THREAD

**Issue by mohammed786** [LoginRadius/cascade#1]
Currently, the CSS if not up to the mark, you can make a good UI out of it.

**Comment by d2Anubis** [comment]
I would like to work on this.

**Comment by chaitanya4vedi** [comment]
I want to help on this

**Comment by mohammed786** [comment]
Hey @chaitanya4vedi , Its because we are only allowing the LoginRadius team members to create an account on this portal.

To set up your own login page create an [LoginRadius App For Free](https://accounts.loginradius.com/auth.aspx?action=register&return_url=https://dashboard.loginradius.com/login) and replace the `APP_URL` in the `src\utils\config.ts` which you will receive on creating a **free account**.

**Comment by chaitanya4vedi** [comment]
> Hey @chaitanya4vedi , Its because we are only allowing the LoginRadius team members to create an account on this portal.
> 
> To set up your own login page create an [LoginRadius App For Free](https://accounts.loginradius.com/auth.aspx?action=register&return_url=https://dashboard.loginradius.com/login) and replace the `APP_URL` in the `src\utils\config.ts` which you will receive on creating a **free account**.
> 
> Feel free to ask any more queries you have.
> 
> Thanks

Got it. Thanks. Please Assign me this, I am interested in it.

**Comment by mohammed786** [comment]
Hey, @chaitanya4vedi 

Sure you can take this up

**Comment by chaitanya4vedi** [comment]
> Hey, @chaitanya4vedi 
> 
> Sure you can take this up

Hi, @mohammed786
No I can't take this as of now.
I am on other tasks you assigned. As soon as I finish that, if no one takes this then I will do it.

**Comment by mohammed786** [comment]
Okay sure

**Comment by BhuwanChandra** [comment]
@mohammed786 I would like to work on this issue.

**Comment by mohammed786** [comment]
Sure @BhuwanChandra , Assigned to you. 

As part of hacktoberfest, LoginRadius is also giving free swags and goodies to its contributors. Please check out our [Hacktoberfest Page](https://www.loginradius.com/engineering/page/hacktoberfest2020) and fill the form mentioned there to become eligible for free swags. :)

**Comment by BhuwanChandra** [comment]
@mohammed786 I have done the local setup of the project, can you provide some more details about the issue like what exactly I need to improve and what's expected in the pull request?

**Comment by mohammed786** [comment]
Seems like the issue has been closed with this #14

**Comment by mohammed786** [comment]
#14
