### ISSUE TITLE
Display a default image if image isn't received from github.

### ISSUE THREAD

**Issue by OmkarPh** [LoginRadius/cascade#10]
I have seen that some developer's profiles are not available due to some reason, as shown:
![image](https://user-images.githubusercontent.com/48476025/94669429-d319e280-032e-11eb-986f-3b35dceedba7.png)

It would be good if some default pic could be shown similar to this:
[Default profile pic](https://www.dreamstime.com/stock-illustration-person-user-account-flat-icon-round-colorful-button-avatar-circular-vector-sign-shadow-effect-style-design-image92997519)

Can anybody assign this to me, I'm interested to do this.

**Comment by mohammed786** [comment]
Hey @OmkarPh ,

The issue is already there regarding the same - https://github.com/LoginRadius/cascade/issues/4 and someone is working on that.

**Comment by OmkarPh** [comment]
Ohh, I thought it's not addressed yet, sorry for that :)
