### ISSUE TITLE
Convert the GitHub profile HTML page into a React component

### ISSUE THREAD

**Issue by t0xic0der** [LoginRadius/cascade#18]
Use the progress made so far in this PR https://github.com/LoginRadius/cascade/pull/11 to convert the HTML document (along with the included JavaScript modules in it) to a React component.

**Comment by t0xic0der** [comment]
@s-katte See if this issue is up your alley.

**Comment by s-katte** [comment]
Hi, This can be handled by me, could you assign it to me, please.

**Comment by mohammed786** [comment]
Sure @s-katte, Issue assigned to you.

As part of hacktoberfest, LoginRadius is also giving free swags and goodies to its contributors. Please check out our [Hacktoberfest Page](https://www.loginradius.com/engineering/page/hacktoberfest2020) and fill the form mentioned there to become eligible for free swags. :)

**Comment by DhairyaSethi** [comment]
Hey, I can take up this issue if there's still any help needed. Thanks.
