### ISSUE TITLE
Add fallback image in people's page

### ISSUE THREAD

**Issue by mohammed786** [LoginRadius/cascade#4]
Need to add the fallback gravatar image in [People Page](http://localhost:3000/people) if the image fails to load.

**Comment by vishkrish200** [comment]
hey,
Can I take up this issue?

**Comment by mohammed786** [comment]
Hi, @vishkrish200 assigned this task to you.

As part of hacktoberfest, LoginRadius is also giving free swags and goodies to its contributors. Please check out our [Hacktoberfest Page](https://www.loginradius.com/engineering/page/hacktoberfest2020) and fill the form mentioned there to become eligible for free swags. :)

**Comment by vishkrish200** [comment]
hey,
I am unable to create an account and login to the domain on running the website on localhost:3000. 
How do I access the People Page?

**Comment by mohammed786** [comment]
Hey @vishkrish200 

Please take a pull and check now.

**Comment by OmkarPh** [comment]
**Hi there,
I have worked out this issue as you can see here:**

![image](https://user-images.githubusercontent.com/48476025/94694839-e2ab2280-0352-11eb-9f31-99bab0026e40.png)

![image](https://user-images.githubusercontent.com/48476025/94694872-eb035d80-0352-11eb-8a54-1abcc9e65eab.png)

**I used onError event listeners for tackling this issue.
My code is completely ready to submit a PR, but I really want this PR to be counted for hacktoberfest therefore, can you guys wait till tomorrow, I will submit the PR tomorrow morning itself.**

I hope it is OK.

**Comment by OmkarPh** [comment]
Hi @mohammed786 
I have made a PR for this issue, can you checkout that and tell if there is anything that I can improve/change.

**Comment by mohammed786** [comment]
Looks Good, thanks for contributing.

**Comment by OmkarPh** [comment]
It was my pleasure.
It's my first contribution in any Organization.
Brilliant code base, loved the challenge 😄
